### ISSUE TITLE
GDPR Regulations 

### ISSUE THREAD

**Issue by dchaudhari13** [FLAIR-THU/VFLAIR#11]
Does VFLAIR follow GDPR protocols and regulations?

**Comment by LindaLydia** [comment]
VFLAIR is a VFL platform which allows multi-party collaborative learning without sharing each party’s local data. As each party’s local data and local model are kept secrete locally, data privacy and model privacy are guaranteed. 
However, currently VFLAIR does not include data authorization or management (e.g. private data transfer) principles that are mentioned in the GDPR regulation.
